#ifndef CRYPTO_LEN_H
#define CRYPTO_LEN_H

#define WORD_INBYTES (WORD_SIZE/8)
#define U32_INBYTES 4
#define CT_SEPUB_INBYTES 64

#define MAC_INBYTES 16
#define NONCE_INBYTES 32

#define HASH_INBYTES 32
#define BATCH_INBYTES (LLMI_MAX_OUTPUT_COUNT * (WORD_SIZE/8))
#define SHAREDKEY_INBYTES 16
#define ENCRYPTED_SHAREDKEY_INBYTES (SHAREDKEY_INBYTES + MAC_INBYTES)

// for C^in
#define CIN_INBYTES MAC_INBYTES
#define AIN_INBYTES (2*HASH_INBYTES+U32_INBYTES)

// for encrypted word
#define C_INBYTES (WORD_INBYTES + MAC_INBYTES)
#define A_INBYTES (2*U32_INBYTES + HASH_INBYTES)

// for encrypted instructions f_\nu
#define AF_INBYTES (2*U32_INBYTES + HASH_INBYTES)
#define FLAG_INBYTES 1

#endif